/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.siteview.jsvapi;

public class MyBool {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MyBool(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MyBool obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      swigsvapiJNI.delete_myBool(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setB(boolean value) {
    swigsvapiJNI.myBool_b_set(swigCPtr, this, value);
  }

  public boolean getB() {
    return swigsvapiJNI.myBool_b_get(swigCPtr, this);
  }

  public MyBool() {
    this(swigsvapiJNI.new_myBool(), true);
  }

}
