/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.siteview.jsvapi;

public class MyString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MyString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MyString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      swigsvapiJNI.delete_myString(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setStr(String value) {
    swigsvapiJNI.myString_str_set(swigCPtr, this, value);
  }

  public String getStr() {
    return swigsvapiJNI.myString_str_get(swigCPtr, this);
  }

  public MyString() {
    this(swigsvapiJNI.new_myString(), true);
  }

}
