/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.siteview.jsvapi;

import java.util.Random;

import org.ofbiz.base.util.Debug;

public class swigsvapi {
	public static final String module = swigsvapi.class.getName();
	private static Random RANDOM = new Random(System.currentTimeMillis());

	public static void swig_test1() {
		swigsvapiJNI.swig_test1();
	}

	public static boolean swig_GetUnivData(ForestMap fmap, StringMap inwhat,
			myString estr) {
		return swigsvapiJNI.swig_GetUnivData(ForestMap.getCPtr(fmap),
				fmap, StringMap.getCPtr(inwhat), inwhat,
				myString.getCPtr(estr), estr);
	}

	public static boolean swig_SubmitUnivData(ForestMap fmap, StringMap inwhat,
			myString estr) {
		return swigsvapiJNI
				.swig_SubmitUnivData(ForestMap.getCPtr(fmap), fmap, StringMap
						.getCPtr(inwhat), inwhat, myString.getCPtr(estr), estr);
	}

	public static boolean swig_GetForestData(ForestVector fvec,
			StringMap inwhat, myString estr) {
		return swigsvapiJNI.swig_GetForestData(ForestVector.getCPtr(fvec),
				fvec, StringMap.getCPtr(inwhat), inwhat,
				myString.getCPtr(estr), estr);
	}

	public static boolean swig_SNextKey(StringMap inwhat, myString key,
			myBool first) {
		return swigsvapiJNI.swig_SNextKey(StringMap.getCPtr(inwhat), inwhat,
				myString.getCPtr(key), key, myBool.getCPtr(first), first);
	}

	public static boolean swig_FNextKey(ForestMap fmap, myString key,
			myBool first) {
		return swigsvapiJNI.swig_FNextKey(ForestMap.getCPtr(fmap), fmap,
				myString.getCPtr(key), key, myBool.getCPtr(first), first);
	}

}
