/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.siteview.jsvapi;

public class StringMap {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StringMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      swigsvapiJNI.delete_StringMap(swigCPtr);
    }
    swigCPtr = 0;
  }

  public StringMap() {
    this(swigsvapiJNI.new_StringMap__SWIG_0(), true);
  }

  public StringMap(StringMap arg0) {
    this(swigsvapiJNI.new_StringMap__SWIG_1(StringMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return swigsvapiJNI.StringMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return swigsvapiJNI.StringMap_empty(swigCPtr, this);
  }

  public void clear() {
    swigsvapiJNI.StringMap_clear(swigCPtr, this);
  }

  public String get(String key) {
    return swigsvapiJNI.StringMap_get(swigCPtr, this, key);
  }

  public void set(String key, String x) {
    swigsvapiJNI.StringMap_set(swigCPtr, this, key, x);
  }

  public void del(String key) {
    swigsvapiJNI.StringMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return swigsvapiJNI.StringMap_has_key(swigCPtr, this, key);
  }

}
