/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.siteview.jsvapi;

public class ForestVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ForestVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ForestVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      swigsvapiJNI.delete_ForestVector(swigCPtr);
    }
    swigCPtr = 0;
  }

  public ForestVector() {
    this(swigsvapiJNI.new_ForestVector__SWIG_0(), true);
  }

  public ForestVector(long n) {
    this(swigsvapiJNI.new_ForestVector__SWIG_1(n), true);
  }

  public long size() {
    return swigsvapiJNI.ForestVector_size(swigCPtr, this);
  }

  public long capacity() {
    return swigsvapiJNI.ForestVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    swigsvapiJNI.ForestVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return swigsvapiJNI.ForestVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    swigsvapiJNI.ForestVector_clear(swigCPtr, this);
  }

  public void add(StringMap x) {
    swigsvapiJNI.ForestVector_add(swigCPtr, this, StringMap.getCPtr(x), x);
  }

  public StringMap get(int i) {
    return new StringMap(swigsvapiJNI.ForestVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, StringMap val) {
    swigsvapiJNI.ForestVector_set(swigCPtr, this, i, StringMap.getCPtr(val), val);
  }

}
