/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.siteview.jsvapi;

class swigsvapiJNI {
  public final static native void myString_str_set(long jarg1, MyString jarg1_, String jarg2);
  public final static native String myString_str_get(long jarg1, MyString jarg1_);
  public final static native long new_myString();
  public final static native void delete_myString(long jarg1);
  public final static native void myBool_b_set(long jarg1, MyBool jarg1_, boolean jarg2);
  public final static native boolean myBool_b_get(long jarg1, MyBool jarg1_);
  public final static native long new_myBool();
  public final static native void delete_myBool(long jarg1);
  public final static native void swig_test1();
  public final static native boolean swig_GetUnivData(long jarg1, ForestMap jarg1_, long jarg2, StringMap jarg2_, long jarg3, MyString jarg3_);
  public final static native boolean swig_SubmitUnivData(long jarg1, ForestMap jarg1_, long jarg2, StringMap jarg2_, long jarg3, MyString jarg3_);
  public final static native boolean swig_GetForestData(long jarg1, ForestVector jarg1_, long jarg2, StringMap jarg2_, long jarg3, MyString jarg3_);
  public final static native boolean swig_SNextKey(long jarg1, StringMap jarg1_, long jarg2, MyString jarg2_, long jarg3, MyBool jarg3_);
  public final static native boolean swig_FNextKey(long jarg1, ForestMap jarg1_, long jarg2, MyString jarg2_, long jarg3, MyBool jarg3_);
  public final static native long new_StringMap__SWIG_0();
  public final static native long new_StringMap__SWIG_1(long jarg1, StringMap jarg1_);
  public final static native long StringMap_size(long jarg1, StringMap jarg1_);
  public final static native boolean StringMap_empty(long jarg1, StringMap jarg1_);
  public final static native void StringMap_clear(long jarg1, StringMap jarg1_);
  public final static native String StringMap_get(long jarg1, StringMap jarg1_, String jarg2);
  public final static native void StringMap_set(long jarg1, StringMap jarg1_, String jarg2, String jarg3);
  public final static native void StringMap_del(long jarg1, StringMap jarg1_, String jarg2);
  public final static native boolean StringMap_has_key(long jarg1, StringMap jarg1_, String jarg2);
  public final static native void delete_StringMap(long jarg1);
  public final static native long new_ForestMap__SWIG_0();
  public final static native long new_ForestMap__SWIG_1(long jarg1, ForestMap jarg1_);
  public final static native long ForestMap_size(long jarg1, ForestMap jarg1_);
  public final static native boolean ForestMap_empty(long jarg1, ForestMap jarg1_);
  public final static native void ForestMap_clear(long jarg1, ForestMap jarg1_);
  public final static native long ForestMap_get(long jarg1, ForestMap jarg1_, String jarg2);
  public final static native void ForestMap_set(long jarg1, ForestMap jarg1_, String jarg2, long jarg3, StringMap jarg3_);
  public final static native void ForestMap_del(long jarg1, ForestMap jarg1_, String jarg2);
  public final static native boolean ForestMap_has_key(long jarg1, ForestMap jarg1_, String jarg2);
  public final static native void delete_ForestMap(long jarg1);
  public final static native long new_ForestVector__SWIG_0();
  public final static native long new_ForestVector__SWIG_1(long jarg1);
  public final static native long ForestVector_size(long jarg1, ForestVector jarg1_);
  public final static native long ForestVector_capacity(long jarg1, ForestVector jarg1_);
  public final static native void ForestVector_reserve(long jarg1, ForestVector jarg1_, long jarg2);
  public final static native boolean ForestVector_isEmpty(long jarg1, ForestVector jarg1_);
  public final static native void ForestVector_clear(long jarg1, ForestVector jarg1_);
  public final static native void ForestVector_add(long jarg1, ForestVector jarg1_, long jarg2, StringMap jarg2_);
  public final static native long ForestVector_get(long jarg1, ForestVector jarg1_, int jarg2);
  public final static native void ForestVector_set(long jarg1, ForestVector jarg1_, int jarg2, long jarg3, StringMap jarg3_);
  public final static native void delete_ForestVector(long jarg1);
}
